const notifications = [
  {
    id: 1,
    avatar_url: "/images/avatar-mark-webber.webp",
    name: "Mark weber",
    action: "reacted to your post",
    item: "My first tournament today",
    unread: true,
    time: "1m ago",
  },
  {
    id: 2,
    avatar_url: "/images/avatar-angela-gray.webp",
    name: "Angela Gray",
    action: "followed you",
    unread: true,
    time: "5m ago",
  },
  {
    id: 3,
    avatar_url: "/images/avatar-jacob-thompson.webp",
    name: "Jacob Thompson",
    action: "has joined your group",
    item: "Chess Club",
    unread: true,
    time: "1 day ago",
  },
  {
    id: 4,
    avatar_url: "/images/avatar-rizky-hasanuddin.webp",
    name: "Rizky Hasanuddin",
    action: "sent you a private message",
    message:
      "Hello, thanks for setting up the Chess Club. I've been a member for a few weeks now and I'm already having lots of fun and improving my game.",
    unread: true,
    time: "5 days ago",
  },
  {
    id: 4,
    avatar_url: "/images/avatar-kimberly-smith.webp",
    name: "Kimberly Smith",
    action: "commented on your picture",
    your_picture: "image/image-chess.webp",
    unread: false,
    time: "1 week ago",
  },
  {
    id: 4,
    avatar_url: "/images/avatar-nathan-peterson.webp",
    name: "Nathan Peterson",
    action: "reacted to your post",
    item: "5 end-game strategies to increase your win rate",
    unread: false,
    time: "2 weeks ago",
  },
  {
    id: 4,
    avatar_url: "/images/avatar-rizky-hasanuddin",
    name: "Rizky Hasanuddin",
    action: "sent you a private message",
    message:
      "Hello, thanks for setting up the Chess Club. I've been a member for a few weeks now and I'm already having lots of fun and improving my game.",
    unread: true,
    time: "5 days ago",
  },
];
